import type { Course, SourceLicence } from "@/lib/courses/types";
import { conceptHeading } from "@/lib/intake/model";
import library from "./library.json";

/**
 * The preloaded library: real subjects, from real textbooks, already built.
 *
 * A student who opens VIVA for the first time should have something worth
 * studying in front of them before they upload anything. These subjects are
 * chapters of openly licensed textbooks — the passages are the book's own
 * words, the concept map and the questions were written by a model reading
 * those passages, and each one records `builtBy: "model"` so the app says so
 * rather than implying a person wrote it.
 *
 * The file is generated by `npx tsx scripts/seed-corpus.mjs`, which refuses
 * any book that is not CC BY 4.0 and copies the attribution off the source.
 * Nothing here is hand-edited: change the script, re-run it, commit the JSON.
 */

/**
 * Concept names arrive as headings, whenever the subject was generated.
 *
 * The seeder applies `conceptHeading` on the way in, but this file is filled
 * over many runs — one subject a day when the provider's budget allows — so it
 * holds entries written before that rule existed, and it will hold entries
 * written by whatever model has budget next. Two of the shipped subjects came
 * back with "cell" and "resolution" as concept names, which the app renders as
 * the heading of a card. Reapplying the same rule here costs nothing when the
 * name is already a heading and means the library cannot ship half-capitalised
 * again, whatever wrote it. It changes presentation only: the word is still the
 * one the model took from the book.
 */
/**
 * An answer key may not demand a word the passages never use.
 *
 * Audited across the shipped library: 26 of 153 questions required a keyword
 * absent from their own source. A student reading BIO4 answers "magnification
 * makes it bigger" and loses a point because the key wants "enlarges"; CHEM1
 * wants "synthesis" and ALG3 wants "no repeats", neither of which appears in
 * the material the student was given. That is the product marking someone down
 * for not guessing a synonym, on material it chose.
 *
 * Unsupported keywords are dropped as long as one supported keyword survives.
 * The first cut of this kept the whole key whenever fewer than two survived,
 * on the theory that a one-word key is a keyword hunt — but that left PSY8
 * demanding "motor" and STAT201 demanding "third", neither of which the
 * student's passages contain. A short key is a weaker grader; an impossible
 * key is an unfair one, and unfair is worse. Only a key with nothing supported
 * at all is left alone, because a key of nothing cannot grade. This changes
 * what is *demanded*, never what is asked, and it cannot invent a keyword.
 *
 * The right long-term fix is in the generator, but the library is filled one
 * subject at a time as provider budget allows, so a load-time rule is what
 * stops the next batch shipping the same defect.
 */
const MIN_KEYWORDS = 1;

function groundedKeywords(required: string[], body: string): string[] {
  if (!required.length) return required;
  const supported = required.filter((k) =>
    k
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, " ")
      .split(/\s+/)
      .some((w) => w.length > 2 && body.includes(w))
  );
  return supported.length >= MIN_KEYWORDS ? supported : required;
}

export const CORPUS: Course[] = (library.subjects as unknown as Course[]).map((course) => {
  const body = course.sources
    .flatMap((s) => s.chunks)
    .map((c) => c.text)
    .join(" ")
    .toLowerCase();
  return {
    ...course,
    concepts: course.concepts.map((c) => ({ ...c, name: conceptHeading(c.name) })),
    examQuestions: (course.examQuestions ?? []).map((q) => ({
      ...q,
      requiredKeywords: groundedKeywords(q.requiredKeywords ?? [], body),
    })),
  };
});

export const CORPUS_GENERATED_AT: string = library.generatedAt;

/** Every distinct licence in the library, for one attribution list on a page. */
export function corpusLicences(): SourceLicence[] {
  const seen = new Map<string, SourceLicence>();
  for (const course of CORPUS) {
    for (const source of course.sources) {
      if (source.licence) seen.set(`${source.licence.workTitle}|${source.licence.name}`, source.licence);
    }
  }
  return [...seen.values()].sort((a, b) => a.workTitle.localeCompare(b.workTitle));
}
