import type { Course, SourceLicence } from "@/lib/courses/types";
import { conceptHeading } from "@/lib/intake/model";
import library from "./library.json";

/**
 * The preloaded library: real subjects, from real textbooks, already built.
 *
 * A student who opens VIVA for the first time should have something worth
 * studying in front of them before they upload anything. These subjects are
 * chapters of openly licensed textbooks — the passages are the book's own
 * words, the concept map and the questions were written by a model reading
 * those passages, and each one records `builtBy: "model"` so the app says so
 * rather than implying a person wrote it.
 *
 * The file is generated by `npx tsx scripts/seed-corpus.mjs`, which refuses
 * any book that is not CC BY 4.0 and copies the attribution off the source.
 * Nothing here is hand-edited: change the script, re-run it, commit the JSON.
 */

/**
 * Concept names arrive as headings, whenever the subject was generated.
 *
 * The seeder applies `conceptHeading` on the way in, but this file is filled
 * over many runs — one subject a day when the provider's budget allows — so it
 * holds entries written before that rule existed, and it will hold entries
 * written by whatever model has budget next. Two of the shipped subjects came
 * back with "cell" and "resolution" as concept names, which the app renders as
 * the heading of a card. Reapplying the same rule here costs nothing when the
 * name is already a heading and means the library cannot ship half-capitalised
 * again, whatever wrote it. It changes presentation only: the word is still the
 * one the model took from the book.
 */
export const CORPUS: Course[] = (library.subjects as unknown as Course[]).map((course) => ({
  ...course,
  concepts: course.concepts.map((c) => ({ ...c, name: conceptHeading(c.name) })),
}));

export const CORPUS_GENERATED_AT: string = library.generatedAt;

/** Every distinct licence in the library, for one attribution list on a page. */
export function corpusLicences(): SourceLicence[] {
  const seen = new Map<string, SourceLicence>();
  for (const course of CORPUS) {
    for (const source of course.sources) {
      if (source.licence) seen.set(`${source.licence.workTitle}|${source.licence.name}`, source.licence);
    }
  }
  return [...seen.values()].sort((a, b) => a.workTitle.localeCompare(b.workTitle));
}
