import type { Course, SourceLicence } from "@/lib/courses/types";
import library from "./library.json";

/**
 * The preloaded library: real subjects, from real textbooks, already built.
 *
 * A student who opens VIVA for the first time should have something worth
 * studying in front of them before they upload anything. These subjects are
 * chapters of openly licensed textbooks — the passages are the book's own
 * words, the concept map and the questions were written by a model reading
 * those passages, and each one records `builtBy: "model"` so the app says so
 * rather than implying a person wrote it.
 *
 * The file is generated by `npx tsx scripts/seed-corpus.mjs`, which refuses
 * any book that is not CC BY 4.0 and copies the attribution off the source.
 * Nothing here is hand-edited: change the script, re-run it, commit the JSON.
 */

export const CORPUS: Course[] = library.subjects as unknown as Course[];

export const CORPUS_GENERATED_AT: string = library.generatedAt;

/** Every distinct licence in the library, for one attribution list on a page. */
export function corpusLicences(): SourceLicence[] {
  const seen = new Map<string, SourceLicence>();
  for (const course of CORPUS) {
    for (const source of course.sources) {
      if (source.licence) seen.set(`${source.licence.workTitle}|${source.licence.name}`, source.licence);
    }
  }
  return [...seen.values()].sort((a, b) => a.workTitle.localeCompare(b.workTitle));
}
