import { chromium } from "@playwright/test";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
const page = await ctx.newPage();
page.on("console", (m) => console.log("console", m.type(), m.text().slice(0, 200)));
page.on("response", (r) => { if (r.url().includes("/api/redteam")) console.log("resp", r.status(), r.url()); });
await page.goto("http://localhost:3210/redteam");
await page.getByTestId("begin").click();
await page.getByTestId("room").waitFor();
await page.getByRole("button", { name: "Type instead" }).click();
await page.getByTestId("typed-input").fill("We automatically fail over to a replica.");
await page.getByTestId("typed-input").press("Enter");
await page.waitForTimeout(2500);
console.log(await page.locator(".rt-room").innerText().then((t) => t.slice(0, 600)));
console.log("latest count", await page.getByTestId("latest-verdict").count());
await page.screenshot({ path: "/tmp/claude-0/dbg.png" });
console.log(await page.getByTestId("latest-verdict").evaluate((el)=>{const r=el.getBoundingClientRect();return {d:getComputedStyle(el).display,w:r.width,h:r.height,parent:getComputedStyle(el.parentElement).display}}));
await b.close();
